<div class="container">
	<?php $arr = $this->recentPosts;foreach ($arr as $value): ?>
		<div class="container"><a href="/admin/mybookview/insideview?bookId=<?= $value->getBookId()?>">
			<h3 class="display-5"> <?= $value->getPageHeader()?></h3>
			<p class="text-justify" style="min-height: 300px; overflow-y: scroll;">
				<?= $value->getContents()?>
			</p>
		</a>
		</div>
	<?php endforeach; ?>
	<div class="container">
		<?php if($this->page > 1): ?>
			<a href="/admin?page=<?= $this->page-1?>" class="btn btn-primary">Previous</a>
		<?php endif;?>
		<?php if($this->page < count($arr)): ?>
			<a href="/admin?page=<?= $this->page+1?>" class="btn btn-primary">Next</a>
		<?php endif; ?>
	</div>
</div>