<div id="leftcontainer">
	<div class="leftcontainer-image">
		<img style="width:500px;height:auto" class="img-responsive" src="/images/book.png" alt="Book">
	</div>
</div>
<div id="bannercontainer">
	<div class="wrappertextcont">
		<h1 class="text-center display-1">We Preserve Knowledge</h1>
		<h3 class="text-center display-4">and</h3>
		<h1 class="text-center display-1">Talents</h1>
	</div>
	
</div>