<div class="maincontents">
				<div id="navcontents" style="display:none;float:left;" class="navbutton">
					<ul class="leftnavmenubar">
						<a class="text-center" href="/<?=$this->moduleName ?>/bookcreate" ><li class="leftnavmenu">Create a book</li></a>
						<a class="text-center" href="/<?=$this->moduleName ?>/bookwrite?page=1" ><li class="leftnavmenu">Write in created book</li></a>
						<a class="text-center" href="/<?=$this->moduleName ?>/bookedit?page=1" ><li class="leftnavmenu">Edit a book</li></a>
						<a class="text-center" href="/<?=$this->moduleName ?>/mybookview?page=1" ><li class="leftnavmenu">View my books</li></a>
						<a class="text-center" href="/<?=$this->moduleName ?>/otherbooksview?page=1" ><li class="leftnavmenu">Other user books</li></a>
						<a class="text-center" href="/<?=$this->moduleName ?>/otherusersview?page=1" ><li class="leftnavmenu">Other users</li></a>
					</ul>
				</div>